### ISSUE TITLE
我是个新手，烧录出现报错，需要怎么解决？

### ISSUE THREAD

**Issue by wzh52112** [MokhaLeee/FreeMovement#1]
![4dfc140b03a7499945e033198c61a55](https://github.com/user-attachments/assets/acc2d353-6864-4e5e-a13c-c8b128604701)
如图

**Comment by MokhaLeee** [comment]
you can try to comment out tested prologue chapter

**Comment by wzh52112** [comment]
我的上帝，我不知道怎么操作，我在MyPrologue.event文件试着各种注释，烧录成功了但是打开游戏文件发现白屏

**Comment by wzh52112** [comment]
![PixPin_2024-09-17_12-18-24](https://github.com/user-attachments/assets/79af92b2-ccc0-4689-b2f6-fdbc6640ff33)

**Comment by MokhaLeee** [comment]
这个补丁只允许在纯净的fe8u上做烧录。否则你需要自行做适配

**Comment by wzh52112** [comment]
感谢您的回复，是的，我用的是您的rfe8u，https://tieba.baidu.com/p/7580141620，真是令人苦恼
![image](https://github.com/user-attachments/assets/ba5fd715-2c96-4d97-8de4-df13ad56b1a4)
或者说我过于笨拙了

**Comment by MokhaLeee** [comment]
汉化补丁占用了同样在free space，所以同样会存在冲突。你有必要首先学习feu的通用教程

**Comment by wzh52112** [comment]
哦，是的，我应该在ROM Buildfile.event更换一个空地址，成功了，感谢，祝您中秋愉快
